language: rust
rust:
  - 1.46.0
  - stable
  - beta
  - nightly
stages:
  - ensure format
  - deny warnings
  - test
jobs:
  include:
    - stage: ensure format
      if: branch = develop
      script: cargo +nightly fmt -- --check
    - stage: deny warnings
      if: branch = develop
      script: RUSTFLAGS='-D warnings' cargo build --all-targets
      #TODO: Make sure this includes clippy warnings
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
